load(draw);

draw3d(title = "Greg Orig",
  xu_grid = 10,
  yv_grid = 10,
  nticks = 500,
  view = [60,30], xlabel="x", ylabel="y", zlabel="z",
  xrange = [-1.5, 1.5], yrange = [-1.5, 1.5], zrange = [-1.5, 1.5],
  surface_hide = false,
  parametric_surface(
    0.1*cos(u)*sin(v),
    0.1*sin(u)*sin(v),
    0.1*cos(v),
    u, 0, 2*%pi, v, -%pi, %pi
  ),
  parametric(
    sin(u),
    cos(u),
    (u-5*%pi)/(5*%pi),
    u, 0, 10*%pi
  )
);


